# Generated by Django 3.1.6 on 2021-03-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialissue',
            name='remarks',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
